# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-sqlite-utils',
                'doc_host': 'https://seeM.github.io',
                'git_url': 'https://github.com/seeM/nbdev-sqlite-utils',
                'lib_path': 'nbdev_sqlite_utils'},
  'syms': {'nbdev_sqlite_utils.core': {'nbdev_sqlite_utils.core.foo': ('core.html#foo', 'nbdev_sqlite_utils/core.py')}}}